namespace ForaTeknoloji.Common
{
    /// <summary>
    /// Panel Operasyon Komutları
    /// Not:Seçilen komut setine göre panel komutları oluşturuluyor.
    /// </summary>
    public enum CommandConstants
    {
        CMD_BASE = 2560,

        //Process Commands
        CMD_ZERO = 0,
        CMD_NONE = CMD_BASE + 1,
        CMD_PORT_INIT = CMD_BASE + 2,
        CMD_PORT_LISTEN = CMD_BASE + 3,
        CMD_PORT_CONNECT = CMD_BASE + 4,
        CMD_PORT_CLOSE = CMD_BASE + 5,
        CMD_PORT_TEST = CMD_BASE + 6,
        CMD_TASK_LIST = CMD_BASE + 7,
        CMD_OUT_TIME = CMD_BASE + 10,
        CMD_PORT_WATCH = CMD_BASE + 15,

        //DB Task Commands
        CMD_SND_TIMEGROUP = CMD_BASE + 40,
        CMD_SNDALL_TIMEGROUP = CMD_BASE + 41,
        CMD_RCV_TIMEGROUP = CMD_BASE + 42,
        CMD_RCVALL_TIMEGROUP = CMD_BASE + 43,
        CMD_ERS_TIMEGROUP = CMD_BASE + 44,
        CMD_ERSALL_TIMEGROUP = CMD_BASE + 45,

        CMD_SND_ACCESSGROUP = CMD_BASE + 50,
        CMD_SNDALL_ACCESSGROUP = CMD_BASE + 51,
        CMD_RCV_ACCESSGROUP = CMD_BASE + 52,
        CMD_RCVALL_ACCESSGROUP = CMD_BASE + 53,
        CMD_ERS_ACCESSGROUP = CMD_BASE + 54,
        CMD_ERSALL_ACCESSGROUP = CMD_BASE + 55,

        CMD_SND_USER = CMD_BASE + 60,
        CMD_SND_USER_LU = CMD_BASE + 61,
        CMD_SNDALL_USER = CMD_BASE + 62,
        CMD_SNDALL_USER_LU = CMD_BASE + 63,
        CMD_RCV_USER = CMD_BASE + 64,
        CMD_RCV_USER_LU = CMD_BASE + 65,
        CMD_RCVALL_USER = CMD_BASE + 66,
        CMD_RCVALL_USER_LU = CMD_BASE + 67,
        CMD_ERS_USER = CMD_BASE + 68,
        CMD_ERSALL_USER = CMD_BASE + 69,
        CMD_SND_MAXUSERID = CMD_BASE + 70,

        CMD_SND_LIFTGROUP = CMD_BASE + 80,
        CMD_SNDALL_LIFTGROUP = CMD_BASE + 81,
        CMD_RCV_LIFTGROUP = CMD_BASE + 82,
        CMD_RCVALL_LIFTGROUP = CMD_BASE + 83,
        CMD_ERS_LIFTGROUP = CMD_BASE + 84,
        CMD_ERSALL_LIFTGROUP = CMD_BASE + 85,

        CMD_SND_USERALARM = CMD_BASE + 90,
        CMD_SNDALL_USERALARM = CMD_BASE + 91,
        CMD_RCV_USERALARM = CMD_BASE + 92,
        CMD_RCVALL_USERALARM = CMD_BASE + 93,
        CMD_ERS_USERALARM = CMD_BASE + 94,
        CMD_ERSALL_USERALARM = CMD_BASE + 95,
        CMD_ERS_ALARMFIRE_STATUS = CMD_BASE + 96,
        CMD_ERS_DOORALARM_STATUS = CMD_BASE + 97,

        CMD_SND_GROUPCALENDAR = CMD_BASE + 100,
        CMD_SNDALL_GROUPCALENDAR = CMD_BASE + 101,
        CMD_RCV_GROUPCALENDAR = CMD_BASE + 102,
        CMD_RCVALL_GROUPCALENDAR = CMD_BASE + 103,
        CMD_ERS_GROUPCALENDAR = CMD_BASE + 104,
        CMD_ERSALL_GROUPCALENDAR = CMD_BASE + 105,

        CMD_SND_LOCALCAPACITYCOUNTERS = CMD_BASE + 110,
        CMD_SNDALL_LOCALCAPACITYCOUNTERS = CMD_BASE + 111,
        CMD_RCV_LOCALCAPACITYCOUNTERS = CMD_BASE + 112,
        CMD_RCVALL_LOCALCAPACITYCOUNTERS = CMD_BASE + 113,

        CMD_RCV_MAXINCOUNTERS = CMD_BASE + 120,
        CMD_ERS_MAXINCOUNTERS = CMD_BASE + 121,
        CMD_ERSALL_MAXINCOUNTERS = CMD_BASE + 122,

        CMD_RCV_SAMETAGCOUNTERS = CMD_BASE + 130,
        CMD_ERS_SAMETAGCOUNTERS = CMD_BASE + 131,
        CMD_ERSALL_SAMETAGCOUNTERS = CMD_BASE + 132,

        CMD_RCV_ACCESSCOUNTERS = CMD_BASE + 140,
        CMD_ERS_ACCESSCOUNTERS = CMD_BASE + 141,
        CMD_ERSALL_ACCESSCOUNTERS = CMD_BASE + 142,

        CMD_ERS_APBCOUNTERS = CMD_BASE + 150,
        CMD_ERSALL_APBCOUNTERS = CMD_BASE + 151,

        CMD_SND_RELAYPROGRAM = CMD_BASE + 160,
        CMD_RCV_RELAYPROGRAM = CMD_BASE + 161,
        CMD_ERS_RELAYPROGRAM = CMD_BASE + 162,

        CMD_SND_RTC = CMD_BASE + 170,
        CMD_RCV_RTC = CMD_BASE + 171,

        CMD_RCV_LOGCOUNT = CMD_BASE + 180,
        CMD_ERS_LOGCOUNT = CMD_BASE + 181,
        CMD_RCV_LOGS = CMD_BASE + 182,
        CMD_SND_LOGSETTINGS = CMD_BASE + 183,
        CMD_RCV_LOGSETTINGS = CMD_BASE + 184,

        CMD_RCV_NEWACCESS = CMD_BASE + 190,
        CMD_SND_AUTH = CMD_BASE + 191,

        CMD_SND_GENERALSETTINGS = CMD_BASE + 200,
        CMD_RCV_GENERALSETTINGS = CMD_BASE + 201,
        CMD_RCV_FIRMWAREVERSION = CMD_BASE + 202,

        CMD_SND_DOORTRIGGER = CMD_BASE + 210,
        CMD_SND_DOORFORCEOPEN = CMD_BASE + 211,
        CMD_SND_DOORFORCECLOSE = CMD_BASE + 212,
        CMD_SND_DOORFREE = CMD_BASE + 213,
        CMD_RCV_LOCALINTERLOCK = CMD_BASE + 214,
        CMD_SND_LOCALINTERLOCK = CMD_BASE + 215,

        //Answer Commands
        CMD_OK = CMD_BASE + 401,
        CMD_CANCEL = CMD_BASE + 402,
        CMD_CSERVER_BUSY = CMD_BASE + 403,
        CMD_PORT_DISABLED = CMD_BASE + 404,
        CMD_BAD = CMD_BASE + 405,
        CMD_UNDEFINED_COMMAND = CMD_BASE + 405,
        CMD_NOTFOUND = CMD_BASE + 406,
        CMD_NO_DATA_YET = CMD_BASE + 407,
        CMD_NO_DATA_PICK = CMD_BASE + 408,
        CMD_NOTPROCESSED = CMD_BASE + 409,
        CMD_ACCESS_DENIED = CMD_BASE + 401,

        //Door Commands
        //DOOR-TRIGGER
        CMD_SND_DOOR1_TRIGGER = CMD_BASE + 500,
        CMD_SND_DOOR2_TRIGGER = CMD_BASE + 501,
        CMD_SND_DOOR3_TRIGGER = CMD_BASE + 502,
        CMD_SND_DOOR4_TRIGGER = CMD_BASE + 503,
        CMD_SND_DOOR5_TRIGGER = CMD_BASE + 504,
        CMD_SND_DOOR6_TRIGGER = CMD_BASE + 505,
        CMD_SND_DOOR7_TRIGGER = CMD_BASE + 506,
        CMD_SND_DOOR8_TRIGGER = CMD_BASE + 507,
        CMD_SND_DOOR9_TRIGGER = CMD_BASE + 508,
        CMD_SND_DOOR10_TRIGGER = CMD_BASE + 509,
        CMD_SND_DOOR11_TRIGGER = CMD_BASE + 510,
        CMD_SND_DOOR12_TRIGGER = CMD_BASE + 511,
        CMD_SND_DOOR13_TRIGGER = CMD_BASE + 512,
        CMD_SND_DOOR14_TRIGGER = CMD_BASE + 513,
        CMD_SND_DOOR15_TRIGGER = CMD_BASE + 514,
        CMD_SND_DOOR16_TRIGGER = CMD_BASE + 515,
        CMD_SND_ALARM_TRIGGER = CMD_BASE + 516,
        //DOOR-OPEN
        CMD_SND_DOOR1_OPEN = CMD_BASE + 517,
        CMD_SND_DOOR2_OPEN = CMD_BASE + 518,
        CMD_SND_DOOR3_OPEN = CMD_BASE + 519,
        CMD_SND_DOOR4_OPEN = CMD_BASE + 520,
        CMD_SND_DOOR5_OPEN = CMD_BASE + 521,
        CMD_SND_DOOR6_OPEN = CMD_BASE + 522,
        CMD_SND_DOOR7_OPEN = CMD_BASE + 523,
        CMD_SND_DOOR8_OPEN = CMD_BASE + 524,
        CMD_SND_DOOR9_OPEN = CMD_BASE + 525,
        CMD_SND_DOOR10_OPEN = CMD_BASE + 526,
        CMD_SND_DOOR11_OPEN = CMD_BASE + 527,
        CMD_SND_DOOR12_OPEN = CMD_BASE + 528,
        CMD_SND_DOOR13_OPEN = CMD_BASE + 529,
        CMD_SND_DOOR14_OPEN = CMD_BASE + 530,
        CMD_SND_DOOR15_OPEN = CMD_BASE + 531,
        CMD_SND_DOOR16_OPEN = CMD_BASE + 532,
        CMD_SND_ALARM_OPEN = CMD_BASE + 533,
        //DOOR-CLOSE
        CMD_SND_DOOR1_CLOSE = CMD_BASE + 534,
        CMD_SND_DOOR2_CLOSE = CMD_BASE + 535,
        CMD_SND_DOOR3_CLOSE = CMD_BASE + 536,
        CMD_SND_DOOR4_CLOSE = CMD_BASE + 537,
        CMD_SND_DOOR5_CLOSE = CMD_BASE + 538,
        CMD_SND_DOOR6_CLOSE = CMD_BASE + 539,
        CMD_SND_DOOR7_CLOSE = CMD_BASE + 540,
        CMD_SND_DOOR8_CLOSE = CMD_BASE + 541,
        CMD_SND_DOOR9_CLOSE = CMD_BASE + 542,
        CMD_SND_DOOR10_CLOSE = CMD_BASE + 543,
        CMD_SND_DOOR11_CLOSE = CMD_BASE + 544,
        CMD_SND_DOOR12_CLOSE = CMD_BASE + 545,
        CMD_SND_DOOR13_CLOSE = CMD_BASE + 546,
        CMD_SND_DOOR14_CLOSE = CMD_BASE + 547,
        CMD_SND_DOOR15_CLOSE = CMD_BASE + 548,
        CMD_SND_DOOR16_CLOSE = CMD_BASE + 549,
        CMD_SND_ALARM_CLOSE = CMD_BASE + 550,
        //DOOR-FREE
        CMD_SND_DOOR_FREE = CMD_BASE + 551
    }
}
