using ForaTeknoloji.Entities.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ForaTeknoloji.Entities.DataTransferObjects
{
    public static class ClearPanelSettings
    {
        public static PanelSettings ClearPanel(PanelSettings panelSettings)
        {
            panelSettings.Seri_No = 0;
            panelSettings.Panel_ID = 0;
            panelSettings.Panel_Name = "";
            panelSettings.Panel_Model = null;
            panelSettings.Panel_Expansion = null;
            panelSettings.Panel_Expansion_2 = null;
            panelSettings.Kontrol_Modu = 0;
            panelSettings.Lokal_APB = null;
            panelSettings.Lokal_APB1 = false;
            panelSettings.Lokal_APB2 = false;
            panelSettings.Lokal_APB3 = false;
            panelSettings.Lokal_APB4 = false;
            panelSettings.Lokal_APB5 = false;
            panelSettings.Lokal_APB6 = false;
            panelSettings.Lokal_APB7 = false;
            panelSettings.Lokal_APB8 = false;
            panelSettings.Global_APB = false;
            panelSettings.Global_Bolge_No = null;
            panelSettings.Global_Capacity_Control = false;
            panelSettings.Global_Access_Count_Control = false;
            panelSettings.Global_MaxIn_Count_Control = false;
            panelSettings.Global_Sequental_Access_Control = null;
            panelSettings.Panel_Same_Tag_Block = null;
            panelSettings.Panel_Same_Tag_Block_Type = null;
            panelSettings.Panel_Same_Tag_Block_HourMinSec = null;
            panelSettings.Status_Data_Update = null;
            panelSettings.Status_Data_Update_Type = null;
            panelSettings.Status_Data_Update_Time = null;
            panelSettings.Panel_M1_Role = 0;
            panelSettings.Panel_M2_Role = 0;
            panelSettings.Panel_M3_Role = 0;
            panelSettings.Panel_M4_Role = 0;
            panelSettings.Panel_M5_Role = 0;
            panelSettings.Panel_M6_Role = 0;
            panelSettings.Panel_M7_Role = 0;
            panelSettings.Panel_M8_Role = 0;
            panelSettings.Panel_Alarm_Role = 0;
            panelSettings.Panel_Alarm_Mode_Role_Ok = false;
            panelSettings.Panel_Alarm_Mode = false;
            panelSettings.Panel_Fire_Mode_Role_Ok = false;
            panelSettings.Panel_Fire_Mode = false;
            panelSettings.Panel_Door_Alarm_Role_Ok = null;
            panelSettings.Panel_Alarm_Broadcast_Ok = null;
            panelSettings.Panel_Fire_Broadcast_Ok = null;
            panelSettings.Panel_Door_Alarm_Broadcast_Ok = null;
            panelSettings.Panel_Global_Bolge1 = 1;
            panelSettings.Panel_Global_Bolge2 = 1;
            panelSettings.Panel_Global_Bolge3 = 1;
            panelSettings.Panel_Global_Bolge4 = 1;
            panelSettings.Panel_Global_Bolge5 = 1;
            panelSettings.Panel_Global_Bolge6 = 1;
            panelSettings.Panel_Global_Bolge7 = 1;
            panelSettings.Panel_Global_Bolge8 = 1;
            panelSettings.Panel_Local_Capacity1 = false;
            panelSettings.Panel_Local_Capacity_Clear1 = false;
            panelSettings.Panel_Local_Capacity_Value1 = 0;
            panelSettings.Panel_Local_Capacity2 = false;
            panelSettings.Panel_Local_Capacity_Clear2 = false;
            panelSettings.Panel_Local_Capacity_Value2 = 0;
            panelSettings.Panel_Local_Capacity3 = false;
            panelSettings.Panel_Local_Capacity_Clear3 = false;
            panelSettings.Panel_Local_Capacity_Value3 = 0;
            panelSettings.Panel_Local_Capacity4 = false;
            panelSettings.Panel_Local_Capacity_Clear4 = false;
            panelSettings.Panel_Local_Capacity_Value4 = 0;
            panelSettings.Panel_Local_Capacity5 = false;
            panelSettings.Panel_Local_Capacity_Clear5 = false;
            panelSettings.Panel_Local_Capacity_Value5 = 0;
            panelSettings.Panel_Local_Capacity6 = false;
            panelSettings.Panel_Local_Capacity_Clear6 = false;
            panelSettings.Panel_Local_Capacity_Value6 = 0;
            panelSettings.Panel_Local_Capacity7 = false;
            panelSettings.Panel_Local_Capacity_Clear7 = false;
            panelSettings.Panel_Local_Capacity_Value7 = 0;
            panelSettings.Panel_Local_Capacity8 = false;
            panelSettings.Panel_Local_Capacity_Clear8 = false;
            panelSettings.Panel_Local_Capacity_Value8 = 0;
            panelSettings.Panel_GW1 = 0;
            panelSettings.Panel_GW2 = 0;
            panelSettings.Panel_GW3 = 0;
            panelSettings.Panel_GW4 = 0;
            panelSettings.Panel_IP1 = 0;
            panelSettings.Panel_IP2 = 0;
            panelSettings.Panel_IP3 = 0;
            panelSettings.Panel_IP4 = 0;
            panelSettings.Panel_TCP_Port = 0;
            panelSettings.Panel_Subnet1 = 0;
            panelSettings.Panel_Subnet2 = 0;
            panelSettings.Panel_Subnet3 = 0;
            panelSettings.Panel_Subnet4 = 0;
            panelSettings.Panel_Remote_IP1 = null;
            panelSettings.Panel_Remote_IP2 = null;
            panelSettings.Panel_Remote_IP3 = null;
            panelSettings.Panel_Remote_IP4 = null;
            panelSettings.Lift_Capacity = null;
            panelSettings.Interlock_Active = null;
            panelSettings.Same_Door_Multiple_Reader = null;
            panelSettings.Global_Zone_Interlock_Active = null;
            panelSettings.Panel_Button_Detector = null;
            panelSettings.Panel_Button_Detector_Time = null;
            panelSettings.Offline_Antipassback = false;
            panelSettings.Offline_Blocked_Request = false;
            panelSettings.Offline_Undefined_Transition = false;
            panelSettings.Offline_Manuel_Operations = false;
            panelSettings.Offline_Button_Triggering = false;
            panelSettings.Offline_Scheduled_Transactions = false;
            panelSettings.LocalInterlock_G1_1 = null;
            panelSettings.LocalInterlock_G1_2 = null;
            panelSettings.LocalInterlock_G2_1 = null;
            panelSettings.LocalInterlock_G2_2 = null;
            panelSettings.LocalInterlock_G3_1 = null;
            panelSettings.LocalInterlock_G3_2 = null;
            panelSettings.LocalInterlock_G4_1 = null;
            panelSettings.LocalInterlock_G4_2 = null;
            panelSettings.DHCP_Enabled = false;
            panelSettings.Hastane_Aktif = null;
            panelSettings.Hastane_IP1 = null;
            panelSettings.Hastane_IP2 = null;
            panelSettings.Hastane_IP3 = null;
            panelSettings.Hastane_IP4 = null;
            panelSettings.Hastane_Server_TCP_Port = null;
            panelSettings.Hastane_Lokal_TCP_Port = null;
            panelSettings.Hastane_Acil_Durum_Yesil_Kod = null;
            panelSettings.Hastane_Yesil_Kod_Suresi = null;
            return panelSettings;
        }
    }
}
